pub mod currency;
pub mod error;
pub mod escape;
pub mod ffmpeg;
pub mod gpt;
pub mod jewtube;
pub mod nhentai;
pub mod reddit;
pub mod shorts;
pub mod statics;
pub mod tts;
pub mod urban;
pub mod xkcd;
pub mod yt_audio;
pub mod yt_download;

use teloxide::utils::command::BotCommand;

#[derive(BotCommand)]
#[command(rename = "lowercase", description = "These commands are supported:")]
pub enum Command {
    #[command(description = "displays this text.")]
    Help,
    #[command(description = "returns a youtube shorts video.")]
    Shorts,
    #[command(description = "returns a video with audio of a youtube url")]
    YtDownload(String),
    #[command(description = "returns only the audio of a youtube url")]
    YtAudio(String),
    #[command(description = "returns a random xkcd comic or one with id")]
    Xkcd(String),
    #[command(description = "returns a random nhentai or one with id")]
    Nhentai(String),
    #[command(description = "returns a random post from a chosen subreddit")]
    Reddit(String),
    #[command(description = "returns a random definition of a word from urban dictionary")]
    Urban(String),
    #[command(description = "returns autogenerated text starting with some text")]
    Gpt(String),
    #[command(description = "returns a blog post from jewtube")]
    Jewtube,
    #[command(
        description = "converts currency to some other popular currencies",
        parse_with = "split"
    )]
    Currency { from: String, amount: f64 },
    #[command(description = "uses google translate tts to speak some text")]
    Tts(String),
}
